### ISSUE TITLE
Covidify broken since récent python 3.8.6 update

### ISSUE THREAD

**Issue by Armag67** [AaronWard/coronavirus-analysis#51]
Hello,
Since yesterday's update of my Manjaro stable box (update including also some Python modules), the following command:
```
covidify run --output ~/Documents/Informatique/Python/covidify/france --country="France"
```
Throw this traceback:
```
Traceback (most recent call last):
  File "/home/h2/.local/lib/python3.8/site-packages/covidify/data_prep.py", line 101, in <module>
    df = check_specified_country(df, country)
  File "/home/h2/.local/lib/python3.8/site-packages/covidify/data_prep.py", line 78, in check_specified_country
    country_list = list(map(lambda x:x.lower().strip(), set(df.country.values)))
  File "/home/h2/.local/lib/python3.8/site-packages/covidify/data_prep.py", line 78, in <lambda>
    country_list = list(map(lambda x:x.lower().strip(), set(df.country.values)))
AttributeError: 'float' object has no attribute 'lower'
```
But `covidify list --countries` works perfectly.

Thanks for taking a look and have a nice day.

**Comment by Armag67** [comment]
Good news,
This issue is solved since today upgrade of my distro. List of Python 3 modules upgraded:
```
python-wxpython (4.0.7.2-1 -> 4.0.7.2-3)
python-shiboken2 (5.15.1-1 -> 5.15.1-2)
python-pysmbc (1.0.20-1 -> 1.0.23-1)
python-pip (20.1.1-1 -> 20.2-1)
python-pyopenssl (19.1.0-2)
python-resolvelib (0.4.0-1 -> 0.5.1-1)
python-pikepdf (1.19.3-1 -> 2.1.0-1)
python-pep517 (0.8.2-1 -> 0.9.1-1)
python-more-itertools (8.5.0-1 -> 8.6.0-1)
python-matplotlib (3.3.2-1 -> 3.3.3-1)
python-numpy (1.19.2-1 -> 1.19.4-1)
python-kiwisolver (1.3.0-1 -> 1.3.1-1)
python-html5lib (1.1-1 -> 1.1-4)
python-babel (2.8.0-4 -> 2.8.1-1)
python-pytz (2020.1-2 -> 2020.4-1)
python-attrs (20.2.0-1 -> 20.3.0-1) 
```
